//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_COEBodyTemplate
    {
        public int ID { get; set; }
        public string TemplateName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string COEBodyTemplate { get; set; }
    }
}
