//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmpDependents
    {
        public int DependentID { get; set; }
        public string EmpID { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Relationship { get; set; }
        public string Occupation { get; set; }
        public string MaidenName { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual t_DependentRelation t_DependentRelation { get; set; }
        public virtual t_EmpMaster t_EmpMaster { get; set; }
    }
}
