//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmpMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_EmpMaster()
        {
            this.t_EmpDependents = new HashSet<t_EmpDependents>();
            this.t_EmpReClassification = new HashSet<t_EmpReClassification>();
            this.t_EmpTrainingsSeminars = new HashSet<t_EmpTrainingsSeminars>();
            this.t_EmpWorkExperience = new HashSet<t_EmpWorkExperience>();
        }
    
        public int BatchNo { get; set; }
        public int SerialID { get; set; }
        public string EmpID { get; set; }
        public string ProximityCardID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Sex { get; set; }
        public System.DateTime? BirthDate { get; set; }
        public System.DateTime? HireDate { get; set; }
        public string EmploymentStatus { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string CivilStatus { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string SSSno { get; set; }
        public string PHno { get; set; }
        public string PagIbigNo { get; set; }
        public string TIN { get; set; }
        public byte[] EmpPicture { get; set; }
        public string EmailAddress { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress { get; set; }
        public string Height { get; set; }
        public string HeightUnit { get; set; }
        public string Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<System.DateTime> EndOfWork { get; set; }
        public string HighestEducationalAttainment { get; set; }
        public Nullable<bool> IDissued { get; set; }
        public Nullable<bool> AppointmentPaperIssued { get; set; }
        public Nullable<int> NoOfDependents { get; set; }
        public Nullable<int> ShuttleDestination { get; set; }
        public Nullable<bool> LoaforManagerApproval { get; set; }
        public string InitialEntryBy { get; set; }
        public Nullable<System.DateTime> InitialEntryDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> firstevaluation { get; set; }
        public Nullable<bool> secondevaluation { get; set; }
        public Nullable<bool> thirdevaluation { get; set; }
        public Nullable<bool> LOAforHRmanagerApproval { get; set; }
    
        public virtual t_CivilStatus t_CivilStatus { get; set; }
        public virtual t_DepartmentalSection t_DepartmentalSection { get; set; }
        public virtual t_EducationalAttainment t_EducationalAttainment { get; set; }
        public virtual t_EmpAddress t_EmpAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_EmpDependents> t_EmpDependents { get; set; }
        public virtual t_EmpEducationalBackground t_EmpEducationalBackground { get; set; }
        public virtual t_HeightUnit t_HeightUnit { get; set; }
        public virtual t_Sex t_Sex { get; set; }
        public virtual t_WeightUnit t_WeightUnit { get; set; }
        public virtual t_EmpPrintID t_EmpPrintID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_EmpReClassification> t_EmpReClassification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_EmpTrainingsSeminars> t_EmpTrainingsSeminars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_EmpWorkExperience> t_EmpWorkExperience { get; set; }
        public virtual t_EmpStatus t_EmpStatus { get; set; }
        public virtual t_Nationality t_Nationality { get; set; }
        public virtual t_Position t_Position { get; set; }
        public virtual t_Religion t_Religion { get; set; }
    }
}
