//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmpEducationalBackground
    {
        public string EmpID { get; set; }
        public string ElementarySchool { get; set; }
        public string ElementaryAddress { get; set; }
        public string ElementaryYear { get; set; }
        public string SecondarySchool { get; set; }
        public string SecondaryAddress { get; set; }
        public string SecondaryYear { get; set; }
        public string TertiarySchool { get; set; }
        public string TertiaryAddress { get; set; }
        public string TertiaryYear { get; set; }
        public string TertiaryCourse { get; set; }
        public string VocationalSchool { get; set; }
        public string VocationalAddress { get; set; }
        public string VocationalYear { get; set; }
        public string VocationalCourse { get; set; }
        public string PostGraduateSchool { get; set; }
        public string PostGraduateAddress { get; set; }
        public string PostGraduateYear { get; set; }
        public string PostGraduateCourse { get; set; }
        public bool IsLicensed { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual t_EmpMaster t_EmpMaster { get; set; }
    }
}
