//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmpTrainingsSeminars
    {
        public string EmpID { get; set; }
        public string ConductedBy { get; set; }
        public string TrainingVenue { get; set; }
        public string TrainingName { get; set; }
        public Nullable<System.DateTime> TrainingFrom { get; set; }
        public Nullable<System.DateTime> TrainingTo { get; set; }
        public string Trainor { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual t_EmpMaster t_EmpMaster { get; set; }
    }
}
